### PR TITLE
Add t2t hsa

### PR DESCRIPTION
**Pull request by hoelzer**
The T2T human genome is more complate than the GrCH38. In the paper, they show that it has 200 Mbp more, closes gaps, and they recently added a more complete Y chromosome. 

I implemented this as another option for auto-download. Tested the pipeline on a small nanopore example data set. 

Currently, Christian in Jena is running tests using some spike-in human data so we will see soon if a more complete human T2T genome helps to decontaminate more human reads (also for the paper). 

If you dont see any problems, we can then also merge this (into `dev` first, and later `main`, right?)

### CODE REVIEW

**Comment by hoelzer** [comment]
Ah this will fail on the RKI HPC due to restrictions downloading from AWS bucket. I tested this on private hardware. 

Also, I added some error handling for fastqc in case running out of RAM. acutally, I think this was just an RKI HPC hick-up but it does also not hurt to have that.

**Comment by matthuska** [comment]
I'm not 100% sure but you might be able to try this link instead:

https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/914/755/GCF_009914755.1_T2T-CHM13v2.0/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz

NCBI should be whitelisted in most bioinformatics environments, and definitely is on the HPC.

**Comment by hoelzer** [comment]
> I'm not 100% sure but you might be able to try this link instead:
> 
> https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/914/755/GCF_009914755.1_T2T-CHM13v2.0/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz
> 
> NCBI should be whitelisted in most bioinformatics environments, and definitely is on the HPC (I tested with wget).

Oh, great! 

Yes, that would be much better. BUT the NCBI one seems to miss the mitochondrial contig. I would like to have that bc quite some DNA/RNA usually comes from the mt genome. 

Ah but the GenBank version seems to have the mtDNA as well:

image

`wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009/914/755/GCA_009914755.4_T2T-CHM13v2.0/GCA_009914755.4_T2T-CHM13v2.0_genomic.fna.gz`

This should do the trick. 

I will update the PR.

**Comment by hoelzer** [comment]
For documentation, assembly stats of

**GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz** (missing mtDNA)

```bash
sum = 3117275501, n = 24, ave = 129886479.21, largest = 248387328
N50 = 150617247, n = 9
N60 = 135127769, n = 11
N70 = 133324548, n = 13
N80 = 99753195, n = 16
N90 = 80542538, n = 19
N100 = 45090682, n = 24
N_count = 0
Gaps = 0
```

**chm13v2.0.fa** (incl. mtDNA, from the AWS)

```bash
sum = 3117292070, n = 25, ave = 124691682.80, largest = 248387328
N50 = 150617247, n = 9
N60 = 135127769, n = 11
N70 = 133324548, n = 13
N80 = 99753195, n = 16
N90 = 80542538, n = 19
N100 = 16569, n = 25
N_count = 0
Gaps = 0
```

**GCA_009914755.4_T2T-CHM13v2.0_genomic.fna.gz** (incl mtDNA, from NCBI)

```bash
sum = 3117292070, n = 25, ave = 124691682.80, largest = 248387328
N50 = 150617247, n = 9
N60 = 135127769, n = 11
N70 = 133324548, n = 13
N80 = 99753195, n = 16
N90 = 80542538, n = 19
N100 = 16569, n = 25
N_count = 0
Gaps = 0
```

Thus, the T2T AWS genome (chm13v2.0.fa) and the T2T NCBI GenBank genome (GCA_009914755.4_T2T-CHM13v2.0_genomic.fna) should be the same. (and both having the mtDNA contig)

**Comment by hoelzer** [comment]
In this context I also checked if all the other genomes we provide have the mtDNA contig

**Comment by hoelzer** [comment]
PR ready and also RKI HPC compatible now

**Review by matthuska — APPROVED** [review]
LGTM

**Pull request merged**
